import React from "react";

const destinations = [
  {
    country: "Bali, Indonesia",
    museums: false,
    beach: true,
    mountains: true,
    hiking: true,
    jungle: true,
    wildlife: true,
    citybreak: false,
    culturalEscape: true,
    skyscrapers: false,
    art: false,
    paradise: true,
    party: true,
    ancientMonuments: true,
    naturalWonders: true,
    highLife: false,
    desert: false,
    shopping: false,
    image: "https://unsplash.com/photos/eE2trMn-6a0",
    description:
      "Bali Indonesia. Also known as the Land of the Gods, Bali appeals through its sheer natural beauty of looming volcanoes and lush terraced rice fields that exude peace and serenity. Bali enchants with its dramatic dances and colorful ceremonies, its arts, and crafts, to its luxurious beach resorts and exciting nightlife.",
  },

  {
    country: "New Orleans",
    museums: true,
    beach: true,
    mountains: false,
    hiking: false,
    jungle: false,
    wildlife: false,
    citybreak: true,
    culturalEscape: true,
    skyscrapers: true,
    art: true,
    paradise: false,
    party: false,
    ancientMonuments: false,
    naturalWonders: false,
    highLife: true,
    desert: true,
    shopping: true,
    image: "https://unsplash.com/photos/sEoR_ea8KoE",
    description:
      "New Orleans is world-renowned for its distinct music, Creole cuisine, unique dialect, and its annual celebrations and festivals, most notably Mardi Gras. The historic heart of the city is the French Quarter, known for its French and Spanish Creole architecture and vibrant nightlife along Bourbon Street.",
  },

  {
    country: "Kerry, Ireland",
    museums: true,
    beach: false,
    mountains: true,
    hiking: true,
    jungle: false,
    wildlife: false,
    citybreak: false,
    culturalEscape: true,
    skyscrapers: false,
    art: false,
    paradise: false,
    party: false,
    ancientMonuments: true,
    naturalWonders: true,
    highLife: false,
    desert: false,
    shopping: false,
    image: "https://unsplash.com/photos/pQuCwYXXZsk",
    description:
      "The county is bounded on the west by the Atlantic Ocean and on the north by the River Shannon. Kerry is one of the most mountainous regions of Ireland and its three highest mountains, Carrauntoohil, Beenkeragh and Caher, all part of the MacGillycuddy's Reeks range.",
  },

  {
    country: "Marrakesh, Morocco",
    museums: false,
    beach: true,
    mountains: true,
    hiking: false,
    jungle: false,
    wildlife: false,
    citybreak: false,
    culturalEscape: true,
    skyscrapers: false,
    art: false,
    paradise: false,
    party: false,
    ancientMonuments: false,
    naturalWonders: false,
    highLife: false,
    desert: true,
    shopping: false,
    image: "https://unsplash.com/photos/bnLF4mddpkc",
    description:
      "Marrakech is the second largest city of Morocco and is known as the Red City. ... Like many north African cities it is mainly divided into medina which is the old fortified city and a modern city nearby (called Gueliz). The city has a wonder climate with shimmering white snowy winters and warm humid summers.",
  },

  {
    country: "Sydney",
    museums: false,
    beach: true,
    mountains: false,
    hiking: false,
    jungle: false,
    wildlife: false,
    citybreak: false,
    culturalEscape: false,
    skyscrapers: true,
    art: false,
    paradise: false,
    party: true,
    ancientMonuments: false,
    naturalWonders: false,
    highLife: true,
    desert: false,
    shopping: true,
    image: "https://unsplash.com/photos/7Zb7kUyQg1E",
    description:
      "Sydney, a coastal metropolis whose five million residents make it the largest city in Australia is famous for many things. The glittering harbour, complemented by landmarks like the Sydney Opera House and the Sydney Harbour Bridge. The dozens of sun-bathed beaches peppering the spectacular coastline.",
  },

  {
    country: "The Maldives",
    museums: false,
    beach: true,
    mountains: false,
    hiking: false,
    jungle: false,
    wildlife: true,
    citybreak: false,
    culturalEscape: false,
    skyscrapers: false,
    art: false,
    paradise: true,
    party: false,
    ancientMonuments: false,
    naturalWonders: false,
    highLife: false,
    desert: false,
    shopping: false,
    image: "https://unsplash.com/photos/M1ObxvsWVhY",
    description:
      "The Maldives are known as the tropical paradise for reasons such as its beauty. This tropical country has separated islands and islands are surrounded by its own lagoon. Each island has pure white sandy beaches. The sea covers 99% of the Maldives and it is where you can see beautiful fishes and corals.",
  },

  {
    country: "Paris, France",
    museums: true,
    beach: false,
    mountains: false,
    hiking: false,
    jungle: false,
    wildlife: false,
    citybreak: true,
    culturalEscape: false,
    skyscrapers: true,
    art: true,
    paradise: false,
    party: false,
    ancientMonuments: false,
    naturalWonders: false,
    highLife: true,
    desert: false,
    shopping: true,
    image: "https://unsplash.com/photos/t9Td0zfDTwI",
    description:
      "Paris is famous for its cafe culture, the Eiffel Tower, the Louvre, Notre Dame, the Moulin Rouge, pastries, and fashion. Paris is known for having beauty, elegance, and for being a boldly romantic city.",
  },

  {
    country: "Cape Town, South Africa",
    museums: false,
    beach: true,
    mountains: true,
    hiking: true,
    jungle: false,
    wildlife: false,
    citybreak: true,
    culturalEscape: false,
    skyscrapers: false,
    art: false,
    paradise: false,
    party: true,
    ancientMonuments: false,
    naturalWonders: true,
    highLife: true,
    desert: false,
    shopping: true,
    image: "https://unsplash.com/photos/FQ03xcur9As",
    description:
      "Known as the “Mother City”, Cape Town is the oldest city in South Africa. Perched between the ocean and the mountain, with a national park as its heart, there is nowhere like Cape Town. Cape Town, the “Mother City”, is the oldest city in South Africa and has a cultural heritage spanning more than 300 years",
  },

  {
    country: "Dubai, U.A.E",
    museums: false,
    beach: true,
    mountains: false,
    hiking: false,
    jungle: false,
    wildlife: false,
    citybreak: true,
    culturalEscape: false,
    skyscrapers: true,
    art: false,
    paradise: false,
    party: true,
    ancientMonuments: false,
    naturalWonders: false,
    highLife: true,
    desert: true,
    shopping: true,
    image: "https://unsplash.com/photos/DcyL0IoCY0A",
    description:
      "Indulgent, glamorous, and progressive are words that describe Dubai. This United Arab Emirates city is a luxury travel destination for leisure and business travellers. Dubai combines a modern metropolis with a timeless sensibility and Arabian flair.",
  },

  {
    country: "Bora Bora, French Polynesia",
    museums: false,
    beach: true,
    mountains: true,
    hiking: true,
    jungle: true,
    wildlife: true,
    citybreak: false,
    culturalEscape: false,
    skyscrapers: false,
    art: false,
    paradise: true,
    party: true,
    ancientMonuments: false,
    naturalWonders: false,
    highLife: false,
    desert: false,
    shopping: false,
    image: "https://unsplash.com/photos/OH6PkGB4JCU",
    Description:
      "Bora Bora is situated approximately 140 miles (225km) northwest of Tahiti, in the western Leeward group of the Society islands of French Polynesia. It is a rugged, volcanic, mountainous island featuring a large lagoon surrounded by beautiful coral reefs and islets.",
  },

  {
    country: "New York",
    museums: true,
    beach: false,
    mountains: false,
    hiking: false,
    jungle: false,
    wildlife: false,
    citybreak: true,
    culturalEscape: false,
    skyscrapers: true,
    art: true,
    paradise: false,
    party: true,
    ancientMonuments: false,
    naturalWonders: false,
    highLife: true,
    desert: false,
    shopping: true,
    image: "https://unsplash.com/photos/UExx0KnnkjY",
    description:
      "New York is a bustling hub of economic activity, and it's also one of the main centers of US culture. New York is so central to American culture that it permeates almost all media. Whether it's an Avengers film or an iconic TV show like Friends, New York is well-represented in books, comics, music, movies, and more.",
  },

  {
    country: "Dolomites, Italy",
    museums: false,
    beach: false,
    mountains: true,
    hiking: true,
    jungle: false,
    wildlife: false,
    citybreak: false,
    culturalEscape: false,
    skyscrapers: false,
    art: false,
    paradise: false,
    party: false,
    ancientMonuments: false,
    naturalWonders: true,
    highLife: false,
    desert: false,
    shopping: false,
    image: "https://unsplash.com/photos/UgbqncwR5bw",
    description:
      "The site of the Dolomites comprises a mountain range in the northern Italian Alps, numbering 18 peaks which rise to above 3,000 metres and cover 141,903 ha. It features some of the most beautiful mountain landscapes anywhere, with vertical walls, sheer cliffs and a high density of narrow, deep and long valleys.",
  },

  {
    country: "Sossusvlei , Namibia",
    museums: false,
    beach: false,
    mountains: true,
    hiking: true,
    jungle: false,
    wildlife: false,
    citybreak: false,
    culturalEscape: false,
    skyscrapers: false,
    art: false,
    paradise: false,
    party: false,
    ancientMonuments: false,
    naturalWonders: false,
    highLife: false,
    desert: true,
    shopping: false,
    image: "https://unsplash.com/photos/S2Q5mdOrrVc",
    description:
      "Set within the coastal desert of Namibia are the biggest sand dunes in the world. They attract a vast number of travellers each year, many of whom aim to climb up the sands and enjoy a thrilling slide back down. ... Due to its unique red sand, Sossusvlei is a must-see for many people when travelling to Africa.",
  },

  {
    country: "Dubrovnik, Croatia",
    museums: false,
    beach: true,
    mountains: false,
    hiking: false,
    jungle: false,
    wildlife: false,
    citybreak: true,
    culturalEscape: true,
    skyscrapers: false,
    art: false,
    paradise: false,
    party: false,
    ancientMonuments: true,
    naturalWonders: false,
    highLife: false,
    desert: false,
    shopping: false,
    image: "https://unsplash.com/photos/ohoBiu7_KNc",
    description:
      "Popular for its spectacular seafront location on the Dalmatian Coast, coupled with its evocative and historic Old Town district, Dubrovnik is home to Croatia's artistic and intellectual elite and offers numerous cultural activities and festivals. Dubrovnik was the filming location for Kings Landing in the famous series a Game of Thrones. Yes, you can get Game of Thrones tours here!",
  },

  {
    country: "Edinburgh, Scotland",
    museums: true,
    beach: false,
    mountains: false,
    hiking: false,
    jungle: false,
    wildlife: false,
    citybreak: true,
    culturalEscape: true,
    skyscrapers: false,
    art: true,
    paradise: false,
    party: false,
    ancientMonuments: true,
    naturalWonders: false,
    highLife: false,
    desert: false,
    shopping: true,
    image: "https://unsplash.com/photos/S56zN8cV5fk",
    description:
      "The city of Edinburgh is renowned world-wide for its history, architecture, scenery and cultural attractions. Built on a group of hills, it is situated between the Firth of Forth to the north, the Pentland Hills to the south, and the council areas of East Lothian and West Lothian to the east and west.",
  },

  {
    country: "Rome, Italy",
    museums: true,
    beach: false,
    mountains: false,
    hiking: false,
    jungle: false,
    wildlife: false,
    citybreak: true,
    culturalEscape: true,
    skyscrapers: false,
    art: true,
    paradise: false,
    party: false,
    ancientMonuments: true,
    naturalWonders: false,
    highLife: false,
    desert: false,
    shopping: false,
    image: "https://unsplash.com/photos/s87bBFZviAU",
    description:
      "Rome (Italian: Roma), the Eternal City, is the capital and largest city of Italy and of the Lazio region. It is famous for being the home of the ancient Roman Empire, the Seven Hills, La Dolce Vita (the sweet life), the Vatican City and Three Coins in the Fountain.",
  },

  {
    country: "Paro Valley, Bhutan",
    museums: false,
    beach: false,
    mountains: true,
    hiking: true,
    jungle: false,
    wildlife: true,
    citybreak: false,
    culturalEscape: true,
    skyscrapers: false,
    art: false,
    paradise: false,
    party: false,
    ancientMonuments: true,
    naturalWonders: true,
    highLife: false,
    desert: false,
    shopping: false,
    image: "https://unsplash.com/photos/A87rz-MJN_E",
    description:
      "Paro valley extends from the confluence of the Paro Chhu and the Wang Chhu rivers at Chuzom up to Mt. Jomolhari at the Tibetan border to the North. This picturesque region is one of the widest valleys in the kingdom and is covered in fertile rice fields and has a beautiful, crystalline river meandering down the valley.",
  },

  {
    country: "Jaipur, India",
    museums: false,
    beach: false,
    mountains: true,
    hiking: true,
    jungle: false,
    wildlife: true,
    citybreak: false,
    culturalEscape: true,
    skyscrapers: false,
    art: false,
    paradise: false,
    party: false,
    ancientMonuments: true,
    naturalWonders: true,
    highLife: false,
    desert: false,
    shopping: false,
    image: "https://unsplash.com/photos/JKiYfDtQ_aA",
    description:
      "Jaipur, popularly known as the Pink City of India, is the largest city in the state of Rajasthan. It is also the capital of Rajasthan. Known for Hawa Mahal, Jal Mahal, Amer Fort, Jantar Mantar and several other places to visit, Jaipur has numerous stories to tell.",
  },

  {
    country: "Waikato, New Zealand",
    museums: false,
    beach: false,
    mountains: false,
    hiking: true,
    jungle: false,
    wildlife: false,
    citybreak: false,
    culturalEscape: false,
    skyscrapers: false,
    art: false,
    paradise: false,
    party: false,
    ancientMonuments: false,
    naturalWonders: true,
    highLife: false,
    desert: false,
    shopping: false,
    image: "https://unsplash.com/photos/7XKkJVw1d8c",
    description:
      "With incredible landscapes all over the place, a cave filled with glow worms (Waitomo), and the famous Lord of the Ring series being filmed here. There is a neverending list of reasons why you should visit this place. Just the fact that Hobbiton actually exists and is here should be reason enough!",
  },

  {
    country: "Havana, Cuba",
    Museums: false,
    Beach: true,
    Mountains: false,
    Hiking: false,
    Jungle: false,
    Wildlife: false,
    Citybreak: true,
    CulturalEscape: true,
    Skyscrapers: true,
    Art: false,
    Paradise: false,
    Party: false,
    AncientMonuments: false,
    NaturalWonders: false,
    HighLife: false,
    Desert: false,
    Shopping: false,
    Image: "https://unsplash.com/photos/RqMIFcDLeos",
    Description:
      "The canyon-like streets are filled with sleek 1950's American cars and breathtaking Spanish Colonial architecture, it's as though you've walked into a time capsule. Havana may be impoverished but it stands strong as a culturally rich city. This tourist-packed town is known as the gem of the Caribbean",
  },

  {
    country: "Tokyo, Japan",
    museums: false,
    beach: false,
    mountains: true,
    hiking: true,
    jungle: false,
    wildlife: false,
    citybreak: true,
    culturalEscape: true,
    skyscrapers: true,
    art: false,
    paradise: false,
    party: false,
    ancientMonuments: true,
    naturalWonders: true,
    highLife: true,
    desert: false,
    shopping: true,
    image: "https://unsplash.com/photos/_noSmX8Kgoo",
    description:
      "Tokyo is famous for Anime, electronics, manga, and video games. Akihabara is the epicenter if it all. It becomes a jungle of electric lights and colors at night, providing a sensory overload for visitors. Getting lost, window shopping, and photography are top activities here.",
  },
  {
    country: "Antarctica",
    museums: false,
    beach: false,
    mountains: true,
    hiking: true,
    jungle: false,
    wildlife: true,
    citybreak: false,
    culturalEscape: false,
    skyscrapers: false,
    art: false,
    paradise: false,
    party: false,
    ancientMonuments: false,
    naturalWonders: true,
    highLife: false,
    desert: false,
    shopping: false,
    image: "https://unsplash.com/photos/3Xd5j9-drDA",
    description:
      "Antarctica is a desert. It does not rain or snow a lot there. When it snows, the snow does not melt and builds up over many years to make large, thick sheets of ice, called ice sheets. Antarctica is made up of lots of ice in the form of glaciers, ice shelves and icebergs.",
  },
  {
    country: "Vancouver, Canada",
    museums: true,
    beach: false,
    mountains: true,
    hiking: true,
    jungle: false,
    wildlife: false,
    citybreak: true,
    culturalEscape: true,
    skyscrapers: true,
    art: false,
    paradise: false,
    party: false,
    ancientMonuments: false,
    naturalWonders: false,
    highLife: true,
    desert: false,
    shopping: true,
    image: "https://unsplash.com/photos/WHHY-iBp3aI",
    description:
      "Majestic mountains, sparkling ocean, rainforests and beautiful foliage throughout all four seasons make Vancouver one of the most beautiful cities in the world. Canadians are known for our friendly nature, and Vancouver's citizens take great pride in our welcoming, clean, safe streets - day or night, all year round.",
  },
  {
    country: "Los Angeles, USA",
    museums: false,
    beach: true,
    mountains: true,
    hiking: true,
    jungle: false,
    wildlife: false,
    citybreak: true,
    culturalEscape: false,
    skyscrapers: true,
    art: false,
    paradise: false,
    party: true,
    ancientMonuments: false,
    naturalWonders: false,
    highLife: true,
    desert: true,
    shopping: true,
    image: "https://unsplash.com/photos/UC8fvOyG5pU",
    description:
      "The city of Los Angeles (also known simply as L.A., and nicknamed the 'City of Angels') is the most populous city in California. Located on a broad basin in Southern California, the city is surrounded by vast mountain ranges, valleys, forests, beautiful beaches along the Pacific Ocean, and nearby desert.",
  },
  {
    country: "Kruger National Park, South Africa",
    museums: false,
    beach: false,
    mountains: true,
    hiking: true,
    jungle: true,
    wildlife: true,
    citybreak: false,
    culturalEscape: false,
    skyscrapers: false,
    art: false,
    paradise: false,
    party: false,
    ancientMonuments: false,
    naturalWonders: true,
    highLife: false,
    desert: false,
    shopping: false,
    image: "https://unsplash.com/photos/qj4s8GmD71g",
    description:
      "The Greater Kruger National Park is South Africa's premier safari destination: it's the largest wildlife conservancy in Africa, set in one of the most accessible yet unspoilt wilderness areas in South Africa.",
  },
  {
    country: "Santorini, Greece",
    museums: false,
    beach: true,
    mountains: false,
    hiking: false,
    jungle: false,
    wildlife: false,
    citybreak: true,
    culturalEscape: false,
    skyscrapers: false,
    art: false,
    paradise: false,
    party: false,
    ancientMonuments: true,
    naturalWonders: false,
    highLife: true,
    desert: false,
    shopping: false,
    image: "https://unsplash.com/photos/MdTtpxGlrz8",
    description:
      "Santorini is a volcanic island in the Cyclades group of the Greek islands. It is located between Ios and Anafi islands. It is famous for dramatic views, stunning sunsets from Oia town, the strange white aubergine (eggplant), the town of Thira and naturally its very own active volcano.",
  },
  {
    country: "Saint Petersburg, Russia",
    museums: true,
    beach: false,
    mountains: false,
    hiking: false,
    jungle: false,
    wildlife: false,
    citybreak: true,
    culturalEscape: true,
    skyscrapers: false,
    art: false,
    paradise: false,
    party: true,
    ancientMonuments: true,
    naturalWonders: false,
    highLife: false,
    desert: false,
    shopping: false,
    image: "https://unsplash.com/photos/7by0kvTWUjI",
    description:
      "St. Petersburg is a mecca of cultural, historical, and architectural landmarks. Founded by Tsar Peter I (the Great) as Russia's “window on Europe,” it bears the unofficial status of Russia's cultural capital and most European city, a distinction that it strives to retain in its perennial competition with Moscow.",
  },
  {
    country: "Singapore",
    museums: false,
    beach: false,
    mountains: false,
    hiking: false,
    jungle: false,
    wildlife: true,
    citybreak: true,
    culturalEscape: false,
    skyscrapers: true,
    art: false,
    paradise: false,
    party: false,
    ancientMonuments: false,
    naturalWonders: false,
    highLife: true,
    desert: false,
    shopping: true,
    image: "https://unsplash.com/photos/ahSFjjLru4Y",
    description:
      "Singapore's tourism landscape has changed dramatically over the recent years, making the island-city even more vibrant and exciting as a destination. Additions in 2012 include diverse and new tourism products and developments such as the Marina Bay Cruise Centre, W Singapore Sentosa Cove and Gardens by the Bay.",
  },
  {
    country: "London, England",
    museums: true,
    beach: false,
    mountains: false,
    hiking: false,
    jungle: false,
    wildlife: false,
    citybreak: true,
    culturalEscape: false,
    skyscrapers: true,
    art: true,
    paradise: false,
    party: true,
    ancientMonuments: true,
    naturalWonders: false,
    highLife: true,
    desert: false,
    shopping: false,
    image: "https://unsplash.com/photos/tZDtyUrYrFU",
    description:
      "Whether you're looking for art or architecture, food or football, London has been honed into a genuinely incredible city through its 2,000-year history. London is famous for its art, architecture, food and fashion, some of which it does better than anywhere else in the world.",
  },
  {
    country: "Rio de Janeiro, Brazil",
    museums: false,
    beach: true,
    mountains: true,
    hiking: true,
    jungle: false,
    wildlife: false,
    citybreak: true,
    culturalEscape: false,
    skyscrapers: false,
    art: false,
    paradise: false,
    party: true,
    ancientMonuments: true,
    naturalWonders: false,
    highLife: true,
    desert: false,
    shopping: false,
    image: "https://unsplash.com/photos/OkiDIla7K8Q",
    description:
      "Known to Brazilians as 'Cidade Maravilhosa' (The Wonderful City), Rio de Janeiro is always brimming with color, sound, rhythm, and joy, which make it synonymous with Carnival, happiness, and beautiful people. Very few places in the world match the hospitality and natural charm in which Rio is perpetually swathed.",
  },
  {
    country: "Petra, Jordan",
    museums: false,
    beach: false,
    mountains: true,
    hiking: true,
    jungle: false,
    wildlife: false,
    citybreak: false,
    culturalEscape: true,
    skyscrapers: false,
    art: false,
    paradise: false,
    party: false,
    ancientMonuments: true,
    naturalWonders: true,
    highLife: false,
    desert: true,
    shopping: false,
    image: "https://unsplash.com/photos/mYEqvgcY1G4",
    description:
      "Petra is half-built, half-carved into the rock, and is surrounded by mountains riddled with passages and gorges. It is one of the world's most famous archaeological sites, where ancient Eastern traditions blend with Hellenistic architecture.",
  },
  {
    country: "Hong Kong, China",
    museums: true,
    beach: false,
    mountains: true,
    hiking: true,
    jungle: false,
    wildlife: false,
    citybreak: true,
    culturalEscape: true,
    skyscrapers: false,
    art: false,
    paradise: false,
    party: false,
    ancientMonuments: true,
    naturalWonders: false,
    highLife: true,
    desert: false,
    shopping: true,
    image: "https://unsplash.com/photos/4hluhoRJokI",
    description:
      "Hong Kong is best known as a shoppers' paradise. There is, however, so much more to Hong Kong than shopping. Visitors can enjoy views of the city from high altitude, sample local food, celebrate festivals, watch sports competitions, and visit movie settings in the city.",
  },
  {
    country: "Barbados",
    museums: false,
    beach: true,
    mountains: true,
    hiking: true,
    jungle: false,
    wildlife: false,
    citybreak: false,
    culturalEscape: false,
    skyscrapers: false,
    art: false,
    paradise: true,
    party: true,
    ancientMonuments: false,
    naturalWonders: false,
    highLife: false,
    desert: false,
    shopping: false,
    image: "https://unsplash.com/photos/RQ01QwLWBNc",
    description:
      "Barbados is truly a unique tropical tourism destination. A 166 square mile gem of white sand beaches, a complex mix of high-class accommodation, made up of intimate guest-houses, small, medium and large hotels, luxury apartments, villas, and condominiums.",
  },
  {
    country: "Amsterdam, The Netherlands",
    museums: true,
    beach: false,
    mountains: false,
    hiking: false,
    jungle: false,
    wildlife: false,
    citybreak: true,
    culturalEscape: false,
    skyscrapers: false,
    art: true,
    paradise: false,
    party: false,
    ancientMonuments: false,
    naturalWonders: false,
    highLife: false,
    desert: false,
    shopping: false,
    image: "https://unsplash.com/photos/oKc7vCb4SS4",
    description:
      "Amsterdam is one of the greatest small cities in the world. From Amsterdam canals to world-famous Amsterdam museums and historical Amsterdam sights, it is one of the most romantic and beautiful cities in Europe. Canal cruises are a popular way to see the city from the perspective of its canals.",
  },
  {
    country: "Santiago, Chile",
    museums: false,
    beach: false,
    mountains: true,
    hiking: true,
    jungle: false,
    wildlife: false,
    citybreak: true,
    culturalEscape: false,
    skyscrapers: true,
    art: false,
    paradise: false,
    party: false,
    ancientMonuments: false,
    naturalWonders: false,
    highLife: false,
    desert: false,
    shopping: false,
    image: "https://pixabay.com/photos/monument-general-baquedano-1475858/",
    description:
      "Santiago, capital of Chile. It lies on the canalized Mapocho River, with views of high Andean peaks to the east. The city has a downtown core of 19th-century neoclassical architecture and winding side-streets, dotted by art deco, neo-gothic, and other styles.",
  },
  {
    country: "Cairo, Egypt",
    museums: true,
    beach: false,
    mountains: false,
    hiking: false,
    jungle: false,
    wildlife: false,
    citybreak: false,
    culturalEscape: false,
    skyscrapers: false,
    art: false,
    paradise: false,
    party: false,
    ancientMonuments: true,
    naturalWonders: false,
    highLife: false,
    desert: true,
    shopping: false,
    image: "https://unsplash.com/photos/XRcmriVYmA8",
    description:
      "It is one of the largest cities in the world and it is the largest in Africa. Cairo is known as being a very densely populated city as well as being the center of Egypt's culture and politics. It is also located near some of the most famous remnants of Ancient Egypt like the Pyramids of Giza.",
  },
  {
    country: "Copenhagen, Denmark",
    museums: true,
    beach: false,
    mountains: false,
    hiking: false,
    jungle: false,
    wildlife: false,
    citybreak: true,
    culturalEscape: false,
    skyscrapers: false,
    art: false,
    paradise: false,
    party: false,
    ancientMonuments: true,
    naturalWonders: false,
    highLife: false,
    desert: false,
    shopping: false,
    image: "https://unsplash.com/photos/cj9_lderSUk",
    description:
      "The best way to describe Copenhagen over all is that it is a city that breathes Old World charm. Copenhagen is absolutely exploding with cultural events and activities, making it a fun and interesting place to visit whether it is for a family vacation or a romantic getaway.",
  },
  {
    country: "Seoul, South Korea",
    museums: false,
    beach: false,
    mountains: false,
    hiking: false,
    jungle: false,
    wildlife: false,
    citybreak: true,
    culturalEscape: true,
    skyscrapers: true,
    art: true,
    paradise: false,
    party: false,
    ancientMonuments: false,
    naturalWonders: false,
    highLife: true,
    desert: false,
    shopping: true,
    image: "https://unsplash.com/photos/rHvBQyfLPjk",
    description:
      "Seoul has many temples and four major palaces such as Gyeongbokgung, one of the most famous. The city offers many other cultural and artistic attractions, such as the Museum of Art, which features traditional porcelain, textile and jewellery exhibits.",
  },
  {
    country: "Laucala Island Resort, Fiji",
    museums: false,
    beach: true,
    mountains: false,
    hiking: true,
    jungle: true,
    wildlife: true,
    citybreak: false,
    culturalEscape: false,
    skyscrapers: false,
    art: false,
    paradise: true,
    party: false,
    ancientMonuments: false,
    naturalWonders: false,
    highLife: false,
    desert: false,
    shopping: false,
    image: "https://unsplash.com/photos/uAnF-0WLpZc",
    description:
      "Set upon 3,500 exclusive acres Laucala private island resort is set amidst coconut plantations, sandy beaches, rich green mountains and breathtaking natural beauty. True luxury is appreciated in the privacy of the resort’s villas widely spread on the northern tip of the island. Diving in a unique underwater world, rain forest tours, horseback riding, surfing, golfing on the 18-hole championship course, or meeting native artists. Whether you choose to dine in your villa or to visit one of Laucala’s five restaurants and bars, you enjoy dishes based on the freshest produce.",
  },
  {
    country: "Providencia, Colombia",
    museums: false,
    beach: true,
    mountains: false,
    hiking: false,
    jungle: false,
    wildlife: false,
    citybreak: false,
    culturalEscape: false,
    skyscrapers: false,
    art: false,
    paradise: true,
    party: false,
    ancientMonuments: false,
    naturalWonders: false,
    highLife: false,
    desert: false,
    shopping: false,
    image: "https://unsplash.com/photos/pc-Zmc-L1sQ",
    description:
      "When it comes to Caribbean Islands, or top places to see in Colombia, hardly anyone talks about San Andres and Providencia Islands (or Isla de Providencia). San Andres is a little overrun by tourism, so you can skip that one. But Providencia, now that is a Jewel in the Caribbean.",
  },
  {
    country: "Machu Picchu, Peru",
    museums: false,
    beach: false,
    mountains: true,
    hiking: true,
    jungle: true,
    wildlife: false,
    citybreak: false,
    culturalEscape: true,
    skyscrapers: false,
    art: false,
    paradise: false,
    party: false,
    ancientMonuments: true,
    naturalWonders: true,
    highLife: false,
    desert: false,
    shopping: false,
    image: "https://unsplash.com/photos/-6HgP_ekYC4",
    description:
      "Machu Picchu was an Incan retreat for its emperor. Machu Picchu is a 15th-century Inca site located on a ridge between the Huayna Picchu and Machu Picchu mountains in Peru. It sits 7,970 feet (2,430 meters) above sea level on the eastern slope of the Andes and overlooks the Urubamba River hundreds of feet below.",
  },
  {
    country: "Virunga National Park, Democratic Republic of the Congo",
    museums: false,
    beach: false,
    mountains: true,
    hiking: true,
    jungle: true,
    wildlife: true,
    citybreak: false,
    culturalEscape: false,
    skyscrapers: false,
    art: false,
    paradise: false,
    party: false,
    ancientMonuments: false,
    naturalWonders: true,
    highLife: false,
    desert: false,
    shopping: false,
    image: "https://unsplash.com/photos/_Z7QOai_dCE",
    description:
      "Virunga National Park is a UNESCO World Heritage Site located in the east of the Democratic Republic of Congo. Virunga is the continent's most biologically diverse protected area and a national park embarking on an ambitious development programme known as the Virunga Alliance. You can see wild Silverback Gorillas here!",
  },
  {
    country: "Lisbon, Portugal",
    museums: true,
    beach: false,
    mountains: false,
    hiking: false,
    jungle: false,
    wildlife: false,
    citybreak: true,
    culturalEscape: true,
    skyscrapers: false,
    art: true,
    paradise: false,
    party: false,
    ancientMonuments: true,
    naturalWonders: false,
    highLife: true,
    desert: false,
    shopping: false,
    image: "https://unsplash.com/photos/VFzacj8JUzM",
    description:
      "Lisbon is probably best known for its colonialist history, ornate architecture and tradition of Fado music. But some of its best features are in the everyday – spectacular hilltop vistas in Alfama or at St. George's Castle, pleasant year-round weather and friendly locals.",
  },
  {
    country: "Hanoi, Vietnam",
    museums: true,
    beach: true,
    mountains: true,
    hiking: true,
    jungle: false,
    wildlife: false,
    citybreak: false,
    culturalEscape: true,
    skyscrapers: false,
    art: false,
    paradise: false,
    party: false,
    ancientMonuments: true,
    naturalWonders: true,
    highLife: false,
    desert: false,
    shopping: false,
    image: "https://unsplash.com/photos/2sCJgkinvyU",
    description:
      "Hanoi, located on the banks of the Red River, is one of the most ancient capitals in the world, where travellers can find well-preserved colonial buildings, ancient pagodas, and unique museums within the city centre.",
  },
  {
    country: "Hawaii, USA",
    museums: false,
    beach: true,
    mountains: true,
    hiking: true,
    jungle: true,
    wildlife: false,
    citybreak: false,
    culturalEscape: false,
    skyscrapers: false,
    art: false,
    paradise: true,
    party: false,
    ancientMonuments: false,
    naturalWonders: true,
    highLife: false,
    desert: false,
    shopping: false,
    image: "https://unsplash.com/photos/COxhU-8uMTM",
    description:
      "The Hawaiian Islands are easily the most unique place in America, if not the entire world, and that's not just because it's a tropical island chain. ... More than 2,500 miles from the nearest landfall and formed by a series of active volcanoes, the Hawaiian Islands are certainly unique in their geology.",
  },
  {
    country: "Ibiza, Spain",
    museums: false,
    beach: true,
    mountains: false,
    hiking: false,
    jungle: false,
    wildlife: false,
    citybreak: false,
    culturalEscape: false,
    skyscrapers: false,
    art: false,
    paradise: false,
    party: true,
    ancientMonuments: false,
    naturalWonders: false,
    highLife: false,
    desert: false,
    shopping: false,
    image: "https://pixabay.com/photos/ibiza-city-eivissa-alley-spain-4475750/",
    description:
      "One of the most famous, scenic and popular of the Balearic Islands is Ibiza. Although the island's size is relatively small, it is packed with amazing sights, attractions and things to do. Ibiza is widely known for its wild nightlife, but there is also plenty of other exciting things to do during the day.",
  },
  {
    country: "Beijing, China",
    museums: false,
    beach: false,
    mountains: false,
    hiking: false,
    jungle: false,
    wildlife: false,
    citybreak: true,
    culturalEscape: true,
    skyscrapers: true,
    art: false,
    paradise: false,
    party: false,
    ancientMonuments: true,
    naturalWonders: false,
    highLife: false,
    desert: false,
    shopping: false,
    image: "https://unsplash.com/photos/yBroAF1cN3I",
    description:
      "Beijing holds many magnificent sights that set national or even world records, including the Great Wall, the longest man-made structure in the world; the Forbidden City, the largest and best preserved ancient architectural complex in the world; and Tian'anmen Square, the largest famous city square in the world.",
  },
  {
    country: "Budapest, Hungary",
    museums: true,
    beach: false,
    mountains: false,
    hiking: false,
    jungle: false,
    wildlife: false,
    citybreak: true,
    culturalEscape: false,
    skyscrapers: false,
    art: true,
    paradise: false,
    party: false,
    ancientMonuments: true,
    naturalWonders: false,
    highLife: false,
    desert: false,
    shopping: false,
    image: "https://unsplash.com/photos/qnUg1rdnUlk",
    description:
      "Budapest is one of the most photogenic cities in Europe. The dramatic skyline that Budapest is most famous for is peppered with 19th-century architectural wonders alongside the Danube River. Notable landmarks include the majestic riverside Parliament Building and a collection of stunning basilicas.",
  },
  {
    country: "Cinque Terre, Italy",
    museums: false,
    beach: true,
    mountains: false,
    hiking: true,
    jungle: false,
    wildlife: false,
    citybreak: false,
    culturalEscape: true,
    skyscrapers: false,
    art: false,
    paradise: false,
    party: false,
    ancientMonuments: true,
    naturalWonders: false,
    highLife: false,
    desert: false,
    shopping: false,
    image: "https://unsplash.com/photos/aRbhfdbq484",
    description:
      "Cinque Terre is the name of a district that encompasses five glorious towns, where small houses are surrounded by lush nature. Visitors to this district will be fascinated by the beauty of these five small villages, namely: Manarola, Riomaggiore, Corniglia, Vernazza and Monterosso al Mare.",
  },
  {
    country: "Buenos Aires, Argentina",
    museums: false,
    beach: true,
    mountains: false,
    hiking: false,
    jungle: false,
    wildlife: false,
    citybreak: true,
    culturalEscape: false,
    skyscrapers: false,
    art: false,
    paradise: false,
    party: false,
    ancientMonuments: false,
    naturalWonders: false,
    highLife: false,
    desert: false,
    shopping: false,
    image: "https://unsplash.com/photos/VynkVKneWJA",
    description:
      "In 2012, it was the most visited city in South America, and the second-most visited city of Latin America (behind Mexico City). It is known for its preserved Eclectic European architecture and rich cultural life. ... Buenos Aires is a multicultural city, being home to multiple ethnic and religious groups.",
  },
  {
    country: "Las Vegas, USA",
    museums: false,
    beach: false,
    mountains: true,
    hiking: true,
    jungle: false,
    wildlife: false,
    citybreak: true,
    culturalEscape: false,
    skyscrapers: true,
    art: false,
    paradise: false,
    party: true,
    ancientMonuments: false,
    naturalWonders: false,
    highLife: true,
    desert: false,
    shopping: false,
    image: "https://unsplash.com/photos/fxe8jEGCdSg",
    description:
      "The city anchors the Las Vegas Valley metropolitan area and is the largest city within the greater Mojave Desert. Las Vegas is an internationally renowned major resort city, known primarily for its gambling, shopping, fine dining, entertainment, and nightlife.",
  },
  {
    country: "Matterhorn, Switzerland",
    museums: false,
    beach: false,
    mountains: true,
    hiking: true,
    jungle: false,
    wildlife: false,
    citybreak: false,
    culturalEscape: false,
    skyscrapers: false,
    art: false,
    paradise: false,
    party: false,
    ancientMonuments: false,
    naturalWonders: true,
    highLife: false,
    desert: false,
    shopping: false,
    image: "https://unsplash.com/photos/ejzx-XRrLdc",
    description:
      "Out of all of the mountains that make up the Alps, the Matterhorn is probably the best known. Meaning “peak in the meadows” in German, the nearly 15,000-foot-tall mountain straddles the Swiss-Italian border and has long been a bucket list destination for climbers.",
  },
];
